// Code generated by entc, DO NOT EDIT.

package cache

const (
	// Label holds the string label denoting the cache type in the database.
	Label = "cache"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWalks holds the string denoting the walks field in the database.
	FieldWalks = "walks"
	// Table holds the table name of the cache in the database.
	Table = "caches"
)

// Columns holds all SQL columns for cache fields.
var Columns = []string{
	FieldID,
	FieldWalks,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
