// Code generated by entc, DO NOT EDIT.

package desiredschema

const (
	// Label holds the string label denoting the desiredschema type in the database.
	Label = "desired_schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// Table holds the table name of the desiredschema in the database.
	Table = "desired_schemas"
)

// Columns holds all SQL columns for desiredschema fields.
var Columns = []string{
	FieldID,
	FieldAlias,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	AliasValidator func(string) error
	// ValueValidator is a validator for the "value" field. It is called by the builders before save.
	ValueValidator func(string) error
)
