// Code generated by entc, DO NOT EDIT.

package cloud

import (
	"entgo.io/ent/dialect/sql"
	"github.com/yonidavidson/ent-side-effect-hooks-example/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Walks applies equality check predicate on the "walks" field. It's identical to WalksEQ.
func Walks(v int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWalks), v))
	})
}

// WalksEQ applies the EQ predicate on the "walks" field.
func WalksEQ(v int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWalks), v))
	})
}

// WalksNEQ applies the NEQ predicate on the "walks" field.
func WalksNEQ(v int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWalks), v))
	})
}

// WalksIn applies the In predicate on the "walks" field.
func WalksIn(vs ...int) predicate.Cloud {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cloud(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldWalks), v...))
	})
}

// WalksNotIn applies the NotIn predicate on the "walks" field.
func WalksNotIn(vs ...int) predicate.Cloud {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cloud(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldWalks), v...))
	})
}

// WalksGT applies the GT predicate on the "walks" field.
func WalksGT(v int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWalks), v))
	})
}

// WalksGTE applies the GTE predicate on the "walks" field.
func WalksGTE(v int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWalks), v))
	})
}

// WalksLT applies the LT predicate on the "walks" field.
func WalksLT(v int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWalks), v))
	})
}

// WalksLTE applies the LTE predicate on the "walks" field.
func WalksLTE(v int) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWalks), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Cloud) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Cloud) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Cloud) predicate.Cloud {
	return predicate.Cloud(func(s *sql.Selector) {
		p(s.Not())
	})
}
