// Code generated by entc, DO NOT EDIT.

package databaseconfig

const (
	// Label holds the string label denoting the databaseconfig type in the database.
	Label = "database_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// Table holds the table name of the databaseconfig in the database.
	Table = "database_configs"
)

// Columns holds all SQL columns for databaseconfig fields.
var Columns = []string{
	FieldID,
	FieldURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
