// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/yonidavidson/entsideeffecthooksexample/ent/databaseconfig"
)

// DatabaseConfig is the model entity for the DatabaseConfig schema.
type DatabaseConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// URL holds the value of the "URL" field.
	URL string `json:"URL,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DatabaseConfig) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case databaseconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case databaseconfig.FieldURL:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type DatabaseConfig", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DatabaseConfig fields.
func (dc *DatabaseConfig) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case databaseconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			dc.ID = int(value.Int64)
		case databaseconfig.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field URL", values[i])
			} else if value.Valid {
				dc.URL = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this DatabaseConfig.
// Note that you need to call DatabaseConfig.Unwrap() before calling this method if this DatabaseConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (dc *DatabaseConfig) Update() *DatabaseConfigUpdateOne {
	return (&DatabaseConfigClient{config: dc.config}).UpdateOne(dc)
}

// Unwrap unwraps the DatabaseConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dc *DatabaseConfig) Unwrap() *DatabaseConfig {
	tx, ok := dc.config.driver.(*txDriver)
	if !ok {
		panic("ent: DatabaseConfig is not a transactional entity")
	}
	dc.config.driver = tx.drv
	return dc
}

// String implements the fmt.Stringer.
func (dc *DatabaseConfig) String() string {
	var builder strings.Builder
	builder.WriteString("DatabaseConfig(")
	builder.WriteString(fmt.Sprintf("id=%v", dc.ID))
	builder.WriteString(", URL=")
	builder.WriteString(dc.URL)
	builder.WriteByte(')')
	return builder.String()
}

// DatabaseConfigs is a parsable slice of DatabaseConfig.
type DatabaseConfigs []*DatabaseConfig

func (dc DatabaseConfigs) config(cfg config) {
	for _i := range dc {
		dc[_i].config = cfg
	}
}
