// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yonidavidson/entsideeffecthooksexample/ent/databaseconfig"
)

// DatabaseConfigCreate is the builder for creating a DatabaseConfig entity.
type DatabaseConfigCreate struct {
	config
	mutation *DatabaseConfigMutation
	hooks    []Hook
}

// SetURL sets the "URL" field.
func (dcc *DatabaseConfigCreate) SetURL(s string) *DatabaseConfigCreate {
	dcc.mutation.SetURL(s)
	return dcc
}

// Mutation returns the DatabaseConfigMutation object of the builder.
func (dcc *DatabaseConfigCreate) Mutation() *DatabaseConfigMutation {
	return dcc.mutation
}

// Save creates the DatabaseConfig in the database.
func (dcc *DatabaseConfigCreate) Save(ctx context.Context) (*DatabaseConfig, error) {
	var (
		err  error
		node *DatabaseConfig
	)
	if len(dcc.hooks) == 0 {
		if err = dcc.check(); err != nil {
			return nil, err
		}
		node, err = dcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DatabaseConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dcc.check(); err != nil {
				return nil, err
			}
			dcc.mutation = mutation
			if node, err = dcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dcc.hooks) - 1; i >= 0; i-- {
			if dcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dcc *DatabaseConfigCreate) SaveX(ctx context.Context) *DatabaseConfig {
	v, err := dcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcc *DatabaseConfigCreate) Exec(ctx context.Context) error {
	_, err := dcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcc *DatabaseConfigCreate) ExecX(ctx context.Context) {
	if err := dcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dcc *DatabaseConfigCreate) check() error {
	if _, ok := dcc.mutation.URL(); !ok {
		return &ValidationError{Name: "URL", err: errors.New(`ent: missing required field "DatabaseConfig.URL"`)}
	}
	return nil
}

func (dcc *DatabaseConfigCreate) sqlSave(ctx context.Context) (*DatabaseConfig, error) {
	_node, _spec := dcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (dcc *DatabaseConfigCreate) createSpec() (*DatabaseConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &DatabaseConfig{config: dcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: databaseconfig.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: databaseconfig.FieldID,
			},
		}
	)
	if value, ok := dcc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: databaseconfig.FieldURL,
		})
		_node.URL = value
	}
	return _node, _spec
}

// DatabaseConfigCreateBulk is the builder for creating many DatabaseConfig entities in bulk.
type DatabaseConfigCreateBulk struct {
	config
	builders []*DatabaseConfigCreate
}

// Save creates the DatabaseConfig entities in the database.
func (dccb *DatabaseConfigCreateBulk) Save(ctx context.Context) ([]*DatabaseConfig, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dccb.builders))
	nodes := make([]*DatabaseConfig, len(dccb.builders))
	mutators := make([]Mutator, len(dccb.builders))
	for i := range dccb.builders {
		func(i int, root context.Context) {
			builder := dccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DatabaseConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dccb *DatabaseConfigCreateBulk) SaveX(ctx context.Context) []*DatabaseConfig {
	v, err := dccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dccb *DatabaseConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := dccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dccb *DatabaseConfigCreateBulk) ExecX(ctx context.Context) {
	if err := dccb.Exec(ctx); err != nil {
		panic(err)
	}
}
