// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yonidavidson/entsideeffecthooksexample/ent/desiredschema"
)

// DesiredSchemaCreate is the builder for creating a DesiredSchema entity.
type DesiredSchemaCreate struct {
	config
	mutation *DesiredSchemaMutation
	hooks    []Hook
}

// SetAlias sets the "alias" field.
func (dsc *DesiredSchemaCreate) SetAlias(s string) *DesiredSchemaCreate {
	dsc.mutation.SetAlias(s)
	return dsc
}

// SetValue sets the "value" field.
func (dsc *DesiredSchemaCreate) SetValue(s string) *DesiredSchemaCreate {
	dsc.mutation.SetValue(s)
	return dsc
}

// Mutation returns the DesiredSchemaMutation object of the builder.
func (dsc *DesiredSchemaCreate) Mutation() *DesiredSchemaMutation {
	return dsc.mutation
}

// Save creates the DesiredSchema in the database.
func (dsc *DesiredSchemaCreate) Save(ctx context.Context) (*DesiredSchema, error) {
	var (
		err  error
		node *DesiredSchema
	)
	if len(dsc.hooks) == 0 {
		if err = dsc.check(); err != nil {
			return nil, err
		}
		node, err = dsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DesiredSchemaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dsc.check(); err != nil {
				return nil, err
			}
			dsc.mutation = mutation
			if node, err = dsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dsc.hooks) - 1; i >= 0; i-- {
			if dsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dsc *DesiredSchemaCreate) SaveX(ctx context.Context) *DesiredSchema {
	v, err := dsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dsc *DesiredSchemaCreate) Exec(ctx context.Context) error {
	_, err := dsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsc *DesiredSchemaCreate) ExecX(ctx context.Context) {
	if err := dsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dsc *DesiredSchemaCreate) check() error {
	if _, ok := dsc.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "DesiredSchema.alias"`)}
	}
	if v, ok := dsc.mutation.Alias(); ok {
		if err := desiredschema.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "DesiredSchema.alias": %w`, err)}
		}
	}
	if _, ok := dsc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "DesiredSchema.value"`)}
	}
	if v, ok := dsc.mutation.Value(); ok {
		if err := desiredschema.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DesiredSchema.value": %w`, err)}
		}
	}
	return nil
}

func (dsc *DesiredSchemaCreate) sqlSave(ctx context.Context) (*DesiredSchema, error) {
	_node, _spec := dsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (dsc *DesiredSchemaCreate) createSpec() (*DesiredSchema, *sqlgraph.CreateSpec) {
	var (
		_node = &DesiredSchema{config: dsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: desiredschema.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: desiredschema.FieldID,
			},
		}
	)
	if value, ok := dsc.mutation.Alias(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: desiredschema.FieldAlias,
		})
		_node.Alias = value
	}
	if value, ok := dsc.mutation.Value(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: desiredschema.FieldValue,
		})
		_node.Value = value
	}
	return _node, _spec
}

// DesiredSchemaCreateBulk is the builder for creating many DesiredSchema entities in bulk.
type DesiredSchemaCreateBulk struct {
	config
	builders []*DesiredSchemaCreate
}

// Save creates the DesiredSchema entities in the database.
func (dscb *DesiredSchemaCreateBulk) Save(ctx context.Context) ([]*DesiredSchema, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dscb.builders))
	nodes := make([]*DesiredSchema, len(dscb.builders))
	mutators := make([]Mutator, len(dscb.builders))
	for i := range dscb.builders {
		func(i int, root context.Context) {
			builder := dscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesiredSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dscb *DesiredSchemaCreateBulk) SaveX(ctx context.Context) []*DesiredSchema {
	v, err := dscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dscb *DesiredSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := dscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dscb *DesiredSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := dscb.Exec(ctx); err != nil {
		panic(err)
	}
}
