// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/yonidavidson/entsideeffecthooksexample/ent/dogs"
)

// Dogs is the model entity for the Dogs schema.
type Dogs struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dogs) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case dogs.FieldID:
			values[i] = new(sql.NullInt64)
		case dogs.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Dogs", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dogs fields.
func (d *Dogs) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dogs.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		case dogs.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				d.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Dogs.
// Note that you need to call Dogs.Unwrap() before calling this method if this Dogs
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Dogs) Update() *DogsUpdateOne {
	return (&DogsClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Dogs entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Dogs) Unwrap() *Dogs {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dogs is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Dogs) String() string {
	var builder strings.Builder
	builder.WriteString("Dogs(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", name=")
	builder.WriteString(d.Name)
	builder.WriteByte(')')
	return builder.String()
}

// DogsSlice is a parsable slice of Dogs.
type DogsSlice []*Dogs

func (d DogsSlice) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
