// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cloud is the predicate function for cloud builders.
type Cloud func(*sql.Selector)

// Dog is the predicate function for dog builders.
type Dog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
