// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cache is the predicate function for cache builders.
type Cache func(*sql.Selector)

// Dog is the predicate function for dog builders.
type Dog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
